version: '3.8'

services:
  db:
    image: mariadb
    container_name: teambim-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teambim
      MYSQL_USER: teambim
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - team_bim_net

  backend:
    build:
      context: ./TeamBIM-backend
      dockerfile: Dockerfile
    container_name: team_bim_backend
    working_dir: /var/www
    volumes:
      - ./TeamBIM-backend:/var/www
      -  /var/www/vendor
    ports:
      - "9001:9000"
    depends_on:
      - db
    networks:
      - team_bim_net
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: teambim
      DB_USERNAME: teambim
      DB_PASSWORD: secret

  frontend:
    build:
      context: ./TeamBIM-frontend
      dockerfile: Dockerfile
    container_name: team_bim_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./TeamBIM-frontend:/app
      - node_modules_frontend:/app/node_modules
    networks:
      - team_bim_net
    depends_on:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: teambim-php
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: teambim
      PMA_PASSWORD: secret
    networks:
      - team_bim_net

volumes:
  dbdata:
  node_modules_frontend:

networks:
  team_bim_net:
