version: '3.8'

services:
  backend:
    build:
      context: ./TeamBIM-backend
      dockerfile: Dockerfile
    container_name: team_bim_backend
    working_dir: /var/www
    volumes:
      - ./TeamBIM-backend:/var/www
    ports:
      - "9001:9000"
    depends_on:
      - db
    networks:
      - team_bim_net
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: teambim
      DB_USERNAME: teambim
      DB_PASSWORD: secret

  frontend:
    build:
      context: ./TeamBIM-frontend
      dockerfile: Dockerfile
    container_name: team_bim_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./TeamBIM-frontend:/app
      - /app/node_modules
    networks:
      - team_bim_net
    depends_on:
      - backend

  db:
    image: mariadb
    container_name: teambim-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teambim
      MYSQL_USER: teambim
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - team_bim_net

volumes:
  dbdata:

networks:
  team_bim_net:
